name: smocode19/cicd_demo/build-and-test

on:
  workflow_call:


defaults:
  run:
    shell: bash  

env:
  SECRET_KEY: dummy
  # total-runners: 4
  IMAGE_NAME: smocode19-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

  run-parallel-tests:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        group: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest --cov --junit-xml=test-results --splitting-algorithm=least_duration --splits 4 --group ${{ matrix.group }} #run pytest with coverage and junit xml output split into 4 groups
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage${{ matrix.group }}
          path: .coverage
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: junit${{ matrix.group }}
          path: test-results    

  linting:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pylint
        run: pylint polls --exit-zero     
